var config={apiKey:"AIzaSyBuaCPUz5s3Iw_hIdhyMG9GmHczwSBefY8",authDomain:"zventus-6cbba.firebaseapp.com",databaseURL:"https://zventus-6cbba.firebaseio.com",projectId:"zventus-6cbba",storageBucket:"zventus-6cbba.appspot.com",messagingSenderId:"68550919770"};firebase.initializeApp(config);var db=firebase.firestore();var user=firebase.auth().currentUser;var active=!0;var active2=!1;var active3=!1;var active4=!1;var active5=!1;function register(){var date=new Date();var options={month:'short',day:'2-digit'};var options2={hour:'numeric',minute:'numeric'};var resultDate=new Intl.DateTimeFormat('en-GB',options).format(date);var resultTime=new Intl.DateTimeFormat('en-GB',options2).format(date);var email=document.getElementById("email").value;var password=document.getElementById("password").value;if(email.length<8){alert('Please enter an email address.');return}
if(password.length<4){alert('Please enter a password.');return}
firebase.auth().createUserWithEmailAndPassword(email,password).then(function(){var DocRef=db.collection(resultDate).doc(email);var DocRef2=db.collection('userData').doc(email);DocRef2.set({Data:{email:email,registerTime:(resultDate+' '+resultTime),password:password}})
DocRef.set({User:{login:(resultTime+' - '+resultDate),email:email},Timestamps:{inAvai:resultTime,login:resultTime,email:email2}},{merge:!0})}).catch(function(error){var errorCode=error.code;var errorMessage=error.message;console.log(errorCode);console.log(errorMessage)})}
function login(){active=!0;var date=new Date();var options={month:'short',day:'2-digit'};var options2={hour:'numeric',minute:'numeric',second:'numeric'};var resultDate=new Intl.DateTimeFormat('en-GB',options).format(date);var resultTime=new Intl.DateTimeFormat('en-GB',options2).format(date);console.log(resultTime);var email2=document.getElementById("email2").value;var password2=document.getElementById("password2").value;if(email2.length<4){alert('Please enter an email address.');return}
if(password2.length<4){alert('Please enter a password.');return}
firebase.auth().signInWithEmailAndPassword(email2,password2).catch(function(error){var errorCode=error.code;var errorMessage=error.message;if(errorCode==='auth/wrong-password'){alert('Wrong password.')}else{alert(errorMessage)}})
firebase.auth().onAuthStateChanged(function(user){if(user){var DocRef2=db.collection(resultDate).doc(email2);DocRef2.set({User:{email:email2,loginDate:(resultDate+' - '+resultTime)},Timestamps:{inAvai:resultTime,login:resultTime,email:email2},Total:{Available:0,Lunch:0,Break:0,Training:0,Project:0,totalTime:0}},{merge:!0})}})}
function logout(){var date=new Date();var options={month:'short',day:'2-digit'};var options2={hour:'numeric',minute:'numeric',second:'numeric'};var resultDate=new Intl.DateTimeFormat('en-GB',options).format(date);var resultTime=new Intl.DateTimeFormat('en-GB',options2).format(date);var user=firebase.auth().currentUser;var email=user.email;var DocRef=db.collection(resultDate).doc(email);DocRef.get().then(function(doc){var login=doc.data().Timestamps.login;var a=login.split(':');var b=resultTime.split(':');var minutes=(+a[0])*60+(+a[1]);var minutes2=(+b[0])*60+(+b[1]);var math=minutes2-minutes;DocRef.set({User:{email:email,logoutDate:(resultDate+' - '+resultTime),},Total:{totalTime:math},Timestamps:{logout:resultTime}},{merge:!0})})
captureAll();setTimeout(function(){firebase.auth().signOut()},500);setTimeout(resetTest,500)}
firebase.auth().onAuthStateChanged(function(user){if(user){var email=user.email;console.log('user:',email);document.getElementById("color").style.display="none";document.getElementById("user_div").style.display="block";document.getElementById("test").style.display="none";document.getElementById("testAgain").style.display="none";document.getElementById("test10").innerHTML="Welcome"+"!"+" 👨‍💻 ";start_timer()}
else{console.log('No user signed in')
document.getElementById("user_div").style.display="none";document.getElementById("test").style.display="block";document.getElementById("color").style.display="block"}});captAvai=!1;captLunch=!1;captBreak=!1;captTrain=!1;captProj=!1;function captureAvai(){console.log('function captureAvai');captureAll();captAvai=!1;var date=new Date();var options={month:'short',day:'2-digit'};var options2={hour:'numeric',minute:'numeric',second:'numeric'};var resultDate=new Intl.DateTimeFormat('en-GB',options).format(date);var resultTime=new Intl.DateTimeFormat('en-GB',options2).format(date);active=!0;start_timer();active2=!1;active3=!1;active4=!1;active5=!1;var user=firebase.auth().currentUser;var email=user.email;var DocRef2=db.collection(resultDate).doc(email);DocRef2.set({Timestamps:{inAvai:resultTime}},{merge:!0})}
function captureLunch(){console.log('function captureLunch');captureAll();captLunch=!0;var date=new Date();var options={month:'short',day:'2-digit'};var options2={hour:'numeric',minute:'numeric',second:'numeric'};var resultDate=new Intl.DateTimeFormat('en-GB',options).format(date);var resultTime=new Intl.DateTimeFormat('en-GB',options2).format(date);active2=!0;start_timer2();active=!1;active3=!1;active4=!1;active5=!1;var user=firebase.auth().currentUser;var email=user.email;var DocRef2=db.collection(resultDate).doc(email);DocRef2.set({Timestamps:{inLunch:resultTime}},{merge:!0})}
function captureBreak(){captureAll();captBreak=!0;var date=new Date();var options={month:'short',day:'2-digit'};var options2={hour:'numeric',minute:'numeric',second:'numeric'};var resultDate=new Intl.DateTimeFormat('en-GB',options).format(date);var resultTime=new Intl.DateTimeFormat('en-GB',options2).format(date);active3=!0;start_timer3();active=!1;active2=!1;active4=!1;active5=!1;var user=firebase.auth().currentUser;var email=user.email;var DocRef2=db.collection(resultDate).doc(email);DocRef2.set({Timestamps:{inBreak:resultTime}},{merge:!0})}
function captureTrain(){captureAll();captTrain=!0;var date=new Date();var options={month:'short',day:'2-digit'};var options2={hour:'numeric',minute:'numeric',second:'numeric'};var resultDate=new Intl.DateTimeFormat('en-GB',options).format(date);var resultTime=new Intl.DateTimeFormat('en-GB',options2).format(date);active4=!0;start_timer4();active=!1;active2=!1;active3=!1;active5=!1;var user=firebase.auth().currentUser;var email=user.email;var DocRef2=db.collection(resultDate).doc(email);DocRef2.set({Timestamps:{inTrain:resultTime}},{merge:!0})}
function captureProject(){captureAll();captProj=!0;var date=new Date();var options={month:'short',day:'2-digit'};var options2={hour:'numeric',minute:'numeric',second:'numeric'};var resultDate=new Intl.DateTimeFormat('en-GB',options).format(date);var resultTime=new Intl.DateTimeFormat('en-GB',options2).format(date);active5=!0;start_timer5();active=!1;active2=!1;active3=!1;active4=!1;var user=firebase.auth().currentUser;var email=user.email;var DocRef2=db.collection(resultDate).doc(email);DocRef2.set({Timestamps:{inProj:resultTime}},{merge:!0})}
function captureAll(){console.log('captureAll')
var user=firebase.auth().currentUser;var email=user.email;var date=new Date();var options={month:'short',day:'2-digit'};var options2={hour:'numeric',minute:'numeric',second:'numeric'};var resultDate=new Intl.DateTimeFormat('en-GB',options).format(date);var resultTime=new Intl.DateTimeFormat('en-GB',options2).format(date);if(!captAvai){var DocRef2=db.collection(resultDate).doc(email);DocRef2.get().then(function(doc){var inAvai=doc.data().Timestamps.inAvai;var a=inAvai.split(':');var b=resultTime.split(':');var minutes=(+a[0])*60+(+a[1])+(+a[2])/60;var minutes2=(+b[0])*60+(+b[1])+(+b[2])/60;var math=minutes2-minutes
console.log(math);DocRef2.set({Total:{Available:math},Timestamps:{outAvai:resultTime}},{merge:!0})
var math2=doc.data().Total.Available;var math3=math+math2;console.log(math2);console.log(math3);DocRef2.set({Total:{Available:math3},Timestamps:{outAvai:resultTime}},{merge:!0})})
captAvai=!0}
if(captLunch){var DocRef2=db.collection(resultDate).doc(email);DocRef2.get().then(function(doc){var inLunch=doc.data().Timestamps.inLunch;var a=inLunch.split(':');var b=resultTime.split(':');var minutes=(+a[0])*60+(+a[1])+(+a[2])/60;var minutes2=(+b[0])*60+(+b[1])+(+b[2])/60;var math=minutes2-minutes;console.log(math);DocRef2.set({Total:{Lunch:math},Timestamps:{outLunch:resultTime}},{merge:!0})
var math2=doc.data().Total.Lunch;var math3=math+math2;console.log(math2);console.log(math3);DocRef2.set({Total:{Lunch:math3},Timestamps:{outLunch:resultTime}},{merge:!0})})
captLunch=!1}
if(captProj){var DocRef2=db.collection(resultDate).doc(email);DocRef2.get().then(function(doc){var inProj=doc.data().Timestamps.inProj;var a=inProj.split(':');var b=resultTime.split(':');var minutes=(+a[0])*60+(+a[1])+(+a[2])/60;var minutes2=(+b[0])*60+(+b[1])+(+b[2])/60;var math=minutes2-minutes;console.log(math);DocRef2.set({Total:{Project:math},Timestamps:{outProj:resultTime}},{merge:!0})
var math2=doc.data().Total.Project;var math3=math+math2;console.log(math2);console.log(math3);DocRef2.set({Total:{Project:math3},Timestamps:{outProj:resultTime}},{merge:!0})})
captProj=!1}
if(captTrain){var DocRef2=db.collection(resultDate).doc(email);DocRef2.get().then(function(doc){var inTrain=doc.data().Timestamps.inTrain;var a=inTrain.split(':');var b=resultTime.split(':');var minutes=(+a[0])*60+(+a[1])+(+a[2])/60;var minutes2=(+b[0])*60+(+b[1])+(+b[2])/60;var math=minutes2-minutes;console.log(math);DocRef2.set({Total:{Training:math},Timestamps:{outTrain:resultTime}},{merge:!0})
var math2=doc.data().Total.Training;var math3=math+math2;console.log(math2);console.log(math3);DocRef2.set({Total:{Training:math3},Timestamps:{outTrain:resultTime}},{merge:!0})})
captTrain=!1}
if(captBreak){var DocRef2=db.collection(resultDate).doc(email);DocRef2.get().then(function(doc){var inBreak=doc.data().Timestamps.inBreak;var a=inBreak.split(':');var b=resultTime.split(':');var minutes=(+a[0])*60+(+a[1])+(+a[2])/60;var minutes2=(+b[0])*60+(+b[1])+(+b[2])/60;var math=minutes2-minutes;console.log(math);DocRef2.set({Total:{Break:math},Timestamps:{outBreak:resultTime}},{merge:!0})
var math2=doc.data().Total.Break;var math3=math+math2;console.log(math2);console.log(math3);DocRef2.set({Total:{Break:math3},Timestamps:{outBreak:resultTime}},{merge:!0})})
captBreak=!1}}
function resetTest(){document.getElementById("my_timer").innerHTML="00"+":"+"00"+":"+"00";document.getElementById("my_timer2").innerHTML="00"+":"+"00"+":"+"00";document.getElementById("my_timer3").innerHTML="00"+":"+"00"+":"+"00";document.getElementById("my_timer4").innerHTML="00"+":"+"00"+":"+"00";document.getElementById("my_timer5").innerHTML="00"+":"+"00"+":"+"00";active=!1;active2=!1;active3=!1;active4=!1;active5=!1;console.log('Reset done')}