var config={apiKey:"AIzaSyBuaCPUz5s3Iw_hIdhyMG9GmHczwSBefY8",authDomain:"zventus-6cbba.firebaseapp.com",databaseURL:"https://zventus-6cbba.firebaseio.com",projectId:"zventus-6cbba",storageBucket:"zventus-6cbba.appspot.com",messagingSenderId:"68550919770"};firebase.initializeApp(config);var db=firebase.firestore();var user=firebase.auth().currentUser;var active2=!1;var active3=!1;var active4=!1;var active5=!1;var active6=!1;function register(){var date=new Date();var options={month:'short',day:'2-digit'};var options2={hour:'numeric',minute:'numeric'};var resultDate=new Intl.DateTimeFormat('en-GB',options).format(date);var resultTime=new Intl.DateTimeFormat('en-GB',options2).format(date);var email=document.getElementById("email").value;var password=document.getElementById("password").value;if(email.length<8){alert('Please enter an email address.');return}
if(password.length<4){alert('Please enter a password.');return}
firebase.auth().createUserWithEmailAndPassword(email,password).then(function(){var DocRef=db.collection(resultDate).doc(email);var DocRef2=db.collection('userData').doc(email);DocRef2.set({Data:{email:email,registerTime:(resultDate+' '+resultTime),password:password}})
DocRef.set({User:{login:(resultTime+' - '+resultDate),email:email}},{merge:!0})}).catch(function(error){var errorCode=error.code;var errorMessage=error.message;console.log(errorCode);console.log(errorMessage)})}
function out(){firebase.auth().signOut()}
function login(){var date=new Date();var options={month:'short',day:'2-digit'};var options2={hour:'numeric',minute:'numeric',second:'numeric'};var resultDate=new Intl.DateTimeFormat('en-GB',options).format(date);var resultTime=new Intl.DateTimeFormat('en-GB',options2).format(date);console.log(resultTime);var email2=document.getElementById("email2").value;var password2=document.getElementById("password2").value;if(email2.length<4){alert('Please enter an email address.');return}
if(password2.length<4){alert('Please enter a password.');return}
firebase.auth().signInWithEmailAndPassword(email2,password2).catch(function(error){var errorCode=error.code;var errorMessage=error.message;if(errorCode==='auth/wrong-password'){alert('Wrong password.')}else{alert(errorMessage)}})
firebase.auth().onAuthStateChanged(function(user){if(user){var DocRef2=db.collection(resultDate).doc(email2);DocRef2.set({User:{email:email2,loginDate:(resultDate+' - '+resultTime)},Timestamps:{inAvai:resultTime,login:resultTime,email:email2}},{merge:!0})}})}
function logout(){alert('Are you sure you want to log out?');var date=new Date();var options={month:'short',day:'2-digit'};var options2={hour:'numeric',minute:'numeric',second:'numeric'};var resultDate=new Intl.DateTimeFormat('en-GB',options).format(date);var resultTime=new Intl.DateTimeFormat('en-GB',options2).format(date);var user=firebase.auth().currentUser;var email=user.email;var DocRef=db.collection(resultDate).doc(email);DocRef.get().then(function(doc){var login=doc.data().Timestamps.login;var a=login.split(':');var b=resultTime.split(':');var minutes=(+a[0])*60+(+a[1]);var minutes2=(+b[0])*60+(+b[1]);var math=minutes2-minutes;DocRef.set({User:{email:email,logoutDate:(resultDate+' - '+resultTime),},Total:{totalTime:math},Timestamps:{logout:resultTime}},{merge:!0})})
setTimeout(out,500);setTimeout(resetTest,500)}
firebase.auth().onAuthStateChanged(function(user){if(user){var email=user.email;console.log('user:',email);document.getElementById("color").style.display="none";document.getElementById("user_div").style.display="block";document.getElementById("test").style.display="none";document.getElementById("testAgain").style.display="none";document.getElementById("test10").innerHTML="Welcome"+"!"+" 👨‍💻 ";changeState2()}
else{console.log('No user signed in')
document.getElementById("user_div").style.display="none";document.getElementById("test").style.display="block";document.getElementById("color").style.display="block"}});function start_timer2(){if(active2){var timer=document.getElementById("my_timer2").innerHTML;var arr=timer.split(":");var hour=arr[0];var min=arr[1];var sec=arr[2];if(sec==59){if(min==59){hour++;min=0;if(hour<10)hour="0"+hour}else{min++}
if(min<10)min="0"+min;sec=0}else{sec ++;if(sec<10)sec="0"+sec}
document.getElementById("my_timer2").innerHTML=hour+":"+min+":"+sec;setTimeout(start_timer2,1000)}}
function start_timer3(){if(active3){var timer=document.getElementById("my_timer3").innerHTML;var arr=timer.split(":");var hour=arr[0];var min=arr[1];var sec=arr[2];if(sec==59){if(min==59){hour++;min=0;if(hour<10)hour="0"+hour}else{min++}
if(min<10)min="0"+min;sec=0}else{sec ++;if(sec<10)sec="0"+sec}
document.getElementById("my_timer3").innerHTML=hour+":"+min+":"+sec;setTimeout(start_timer3,1000)}}
function start_timer4(){if(active4){var timer=document.getElementById("my_timer4").innerHTML;var arr=timer.split(":");var hour=arr[0];var min=arr[1];var sec=arr[2];if(sec==59){if(min==59){hour++;min=0;if(hour<10)hour="0"+hour}else{min++}
if(min<10)min="0"+min;sec=0}else{sec ++;if(sec<10)sec="0"+sec}
document.getElementById("my_timer4").innerHTML=hour+":"+min+":"+sec;setTimeout(start_timer4,1000)}}
function start_timer5(){if(active5){var timer=document.getElementById("my_timer5").innerHTML;var arr=timer.split(":");var hour=arr[0];var min=arr[1];var sec=arr[2];if(sec==59){if(min==59){hour++;min=0;if(hour<10)hour="0"+hour}else{min++}
if(min<10)min="0"+min;sec=0}else{sec ++;if(sec<10)sec="0"+sec}
document.getElementById("my_timer5").innerHTML=hour+":"+min+":"+sec;setTimeout(start_timer5,1000)}}
function start_timer6(){if(active6){var timer=document.getElementById("my_timer6").innerHTML;var arr=timer.split(":");var hour=arr[0];var min=arr[1];var sec=arr[2];if(sec==59){if(min==59){hour++;min=0;if(hour<10)hour="0"+hour}else{min++}
if(min<10)min="0"+min;sec=0}else{sec ++;if(sec<10)sec="0"+sec}
document.getElementById("my_timer6").innerHTML=hour+":"+min+":"+sec;setTimeout(start_timer6,1000)}}
function changeState2(){if(active2==!1){active2=!0;start_timer2();console.log("Timer 2 has been started")}else{console.log("timmer is on pause")}}
function changeState3(){if(active3==!1){active3=!0;start_timer3();console.log("Timer 3 has been started")}else{console.log("timmer is on pause")}}
function changeState4(){if(active4==!1){active4=!0;start_timer4();console.log("Timer 4 has been started")}else{console.log("timmer is on pause")}}
function changeState5(){if(active5==!1){active5=!0;start_timer5();console.log("Timer 5 has been started")}else{console.log("timmer is on pause")}}
function changeState6(){if(active6==!1){active6=!0;start_timer6();console.log("Timer 6 has been started")}else{console.log("timmer is on pause")}}
captAvai=!0;captLunch=!1;captBreak=!1;captTrain=!1;captProj=!1;saveAvai=!1;saveLunch=!1;saveBreak=!1;saveTrain=!1;saveProj=!1;oneAvai=!1;twoLunch=!1;threeBreak=!1;fourTrain=!1;fiveProj=!1;console.log('oneAvai:',oneAvai);function test(){console.log('test function activated');if(oneAvai){var date=new Date();var options={month:'short',day:'2-digit'};var options2={hour:'numeric',minute:'numeric',second:'numeric'};var resultDate=new Intl.DateTimeFormat('en-GB',options).format(date);var resultTime=new Intl.DateTimeFormat('en-GB',options2).format(date);var user=firebase.auth().currentUser;var email=user.email;var DocRef=db.collection(resultDate).doc(email);if(saveLunch){console.log('save lunch is true')}
if(saveAvai!=captureAvai){console.log('saveAvai != captureAvai')
var DocRef=db.collection(resultDate).doc(email);DocRef.get().then(function(doc){var outAvailable=doc.data().Timestamps.outAvai;var Available=doc.data().Total.Available;var a=outAvailable.split(':');var b=resultTime.split(':');var minutes=(+a[0])*60+(+a[1])+(+a[2])/60;var minutes2=(+b[0])*60+(+b[1])+(+b[2])/60;var math=minutes2-minutes;var math2=math+math2;DocRef.set({Total:{Available2:math2},Timestamps:{outAvai:resultTime}},{merge:!0})})
console.log('save two succesful');oneAvai=!1}}
else{console.log('else: oneAvai is false')}}
function captureAvai(){console.log('function captureAvai');test();captAvai=!0;console.log(saveAvai);var date=new Date();var options={month:'short',day:'2-digit'};var options2={hour:'numeric',minute:'numeric',second:'numeric'};var resultDate=new Intl.DateTimeFormat('en-GB',options).format(date);var resultTime=new Intl.DateTimeFormat('en-GB',options2).format(date);changeState2();active3=!1;active4=!1;active5=!1;active6=!1;var user=firebase.auth().currentUser;var email=user.email;var DocRef2=db.collection(resultDate).doc(email);DocRef2.set({Timestamps:{inAvai:resultTime}},{merge:!0})
if(captLunch){var user=firebase.auth().currentUser;var email=user.email;var DocRef2=db.collection(resultDate).doc(email);DocRef2.get().then(function(doc){var inLunch=doc.data().Timestamps.inLunch;var a=inLunch.split(':');var b=resultTime.split(':');var minutes=(+a[0])*60+(+a[1])+(+a[2])/60;var minutes2=(+b[0])*60+(+b[1])+(+b[2])/60;var math=minutes2-minutes;DocRef2.set({Total:{Lunch:math},Timestamps:{outLunch:resultTime}},{merge:!0})})
captLunch=!1;saveLunch=!0;console.log('saveAvai:',saveAvai);console.log('saveLunch:',saveLunch);oneAvai=!0}
if(captProj){var user=firebase.auth().currentUser;var email=user.email;var DocRef2=db.collection(resultDate).doc(email);DocRef2.get().then(function(doc){var inProj=doc.data().Timestamps.inProj;var a=inProj.split(':');var b=resultTime.split(':');var minutes=(+a[0])*60+(+a[1])+(+a[2])/60;var minutes2=(+b[0])*60+(+b[1])+(+b[2])/60;var math=minutes2-minutes;DocRef2.set({Total:{Project:math},Timestamps:{outProj:resultTime}},{merge:!0})})
captProj=!1;saveProj=!0;test()}
if(captTrain){var user=firebase.auth().currentUser;var email=user.email;var DocRef2=db.collection(resultDate).doc(email);DocRef2.get().then(function(doc){var inTrain=doc.data().Timestamps.inTrain;var a=inTrain.split(':');var b=resultTime.split(':');var minutes=(+a[0])*60+(+a[1])+(+a[2])/60;var minutes2=(+b[0])*60+(+b[1])+(+b[2])/60;var math=minutes2-minutes;DocRef2.set({Total:{Training:math},Timestamps:{outTrain:resultTime}},{merge:!0})})
captTrain=!1;saveTrain=!0;test()}
if(captBreak){var user=firebase.auth().currentUser;var email=user.email;var DocRef2=db.collection(resultDate).doc(email);DocRef2.get().then(function(doc){var inBreak=doc.data().Timestamps.inBreak;var a=inBreak.split(':');var b=resultTime.split(':');var minutes=(+a[0])*60+(+a[1])+(+a[2])/60;var minutes2=(+b[0])*60+(+b[1])+(+b[2])/60;var math=minutes2-minutes;DocRef2.set({Total:{Break:math},Timestamps:{outBreak:inBreak}},{merge:!0})})
captBreak=!1;saveBreak=!0;test()}}
function captureLunch(){console.log('function captureLunch');test();oneAvai=!0;console.log('oneAvai:',oneAvai);captLunch=!0;var date=new Date();var options={month:'short',day:'2-digit'};var options2={hour:'numeric',minute:'numeric',second:'numeric'};var resultDate=new Intl.DateTimeFormat('en-GB',options).format(date);var resultTime=new Intl.DateTimeFormat('en-GB',options2).format(date);changeState3();active2=!1;active4=!1;active5=!1;active6=!1;var user=firebase.auth().currentUser;var email=user.email;var DocRef2=db.collection(resultDate).doc(email);DocRef2.set({Timestamps:{inLunch:resultTime}},{merge:!0})
if(captAvai){var user=firebase.auth().currentUser;var email=user.email;var DocRef2=db.collection(resultDate).doc(email);DocRef2.get().then(function(doc){var inAvai=doc.data().Timestamps.inAvai;var a=inAvai.split(':');var b=resultTime.split(':');var minutes=(+a[0])*60+(+a[1])+(+a[2])/60;var minutes2=(+b[0])*60+(+b[1])+(+b[2])/60;var math=minutes2-minutes;DocRef2.set({Total:{Available:math},Timestamps:{outAvai:resultTime}},{merge:!0})})
captAvai=!1;saveAvai=!0;console.log('captAvai:',captAvai);console.log('saveAvai:',saveAvai)}
if(captProj){var user=firebase.auth().currentUser;var email=user.email;var DocRef2=db.collection(resultDate).doc(email);DocRef2.get().then(function(doc){var inProy=doc.data().Timestamps.inProj;var a=inProy.split(':');var b=resultTime.split(':');var minutes=(+a[0])*60+(+a[1])+(+a[2])/60;var minutes2=(+b[0])*60+(+b[1])+(+b[2])/60;var math=minutes2-minutes;DocRef2.set({Total:{Project:math},Timestamps:{outProj:resultTime}},{merge:!0})})
captProj=!1;saveProj=!0;test()}
if(captTrain){var user=firebase.auth().currentUser;var email=user.email;var DocRef2=db.collection(resultDate).doc(email);DocRef2.get().then(function(doc){var inTrain=doc.data().User.inTrain;var a=inTrain.split(':');var b=resultTime.split(':');var minutes=(+a[0])*60+(+a[1])+(+a[2])/60;var minutes2=(+b[0])*60+(+b[1])+(+b[2])/60;var math=minutes2-minutes;DocRef2.set({Total:{Training:math},Timestamps:{outTrain:resultTime}},{merge:!0})})
captTrain=!1;saveTrain=!0;test()}
if(captBreak){var user=firebase.auth().currentUser;var email=user.email;var DocRef2=db.collection(resultDate).doc(email);DocRef2.get().then(function(doc){var inBreak=doc.data().User.inBreak;var a=inBreak.split(':');var b=resultTime.split(':');var minutes=(+a[0])*60+(+a[1])+(+a[2])/60;var minutes2=(+b[0])*60+(+b[1])+(+b[2])/60;var math=minutes2-minutes;DocRef2.set({Total:{totalBreak:math},Timestamps:{outBreak:resultTime}},{merge:!0})})
captBreak=!1;saveBreak=!0;test()}}
function captureBreak(){captBreak=!0;console.log('saveAvai:',saveAvai);console.log('saveLunch:',saveLunch);var date=new Date();var options={month:'short',day:'2-digit'};var options2={hour:'numeric',minute:'numeric',second:'numeric'};var resultDate=new Intl.DateTimeFormat('en-GB',options).format(date);var resultTime=new Intl.DateTimeFormat('en-GB',options2).format(date);changeState4();active2=!1;active3=!1;active5=!1;active6=!1;var user=firebase.auth().currentUser;var email=user.email;var DocRef2=db.collection(resultDate).doc(email);DocRef2.set({Timestamps:{inBreak:resultTime}},{merge:!0})
if(captAvai){var user=firebase.auth().currentUser;var email=user.email;var DocRef2=db.collection(resultDate).doc(email);DocRef2.get().then(function(doc){var inAvai=doc.data().Timestamps.inAvai;var a=inAvai.split(':');var b=resultTime.split(':');var minutes=(+a[0])*60+(+a[1])+(+a[2])/60;var minutes2=(+b[0])*60+(+b[1])+(+b[2])/60;var math=minutes2-minutes;DocRef2.set({Total:{Available:math},Timestamps:{outAvai:resultTime}},{merge:!0})})
captAvai=!1;saveAvai=!0;test()}
if(captLunch){var user=firebase.auth().currentUser;var email=user.email;var DocRef2=db.collection(resultDate).doc(email);DocRef2.get().then(function(doc){var inLunch=doc.data().Timestamps.inLunch;var a=inLunch.split(':');var b=resultTime.split(':');var minutes=(+a[0])*60+(+a[1])+(+a[2])/60;var minutes2=(+b[0])*60+(+b[1])+(+b[2])/60;var math=minutes2-minutes;DocRef2.set({Total:{Lunch:math},Timestamps:{outLunch:resultTime}},{merge:!0})})
captLunch=!1;saveLunch=!0;test()}
if(captProj){var user=firebase.auth().currentUser;var email=user.email;var DocRef2=db.collection(resultDate).doc(email);DocRef2.get().then(function(doc){var inProy=doc.data().Timestamps.inProy;var a=inProy.split(':');var b=resultTime.split(':');var minutes=(+a[0])*60+(+a[1])+(+a[2])/60;var minutes2=(+b[0])*60+(+b[1])+(+b[2])/60;var math=minutes2-minutes;DocRef2.set({Total:{totalProy:math},Timestamps:{outProj:resultTime}},{merge:!0})})
captProj=!1;saveProj=!0}
if(captTrain){var user=firebase.auth().currentUser;var email=user.email;var DocRef2=db.collection(resultDate).doc(email);DocRef2.get().then(function(doc){var inTrain=doc.data().Timestamps.inTrain;var a=inTrain.split(':');var b=resultTime.split(':');var minutes=(+a[0])*60+(+a[1])+(+a[2])/60;var minutes2=(+b[0])*60+(+b[1])+(+b[2])/60;var math=minutes2-minutes;DocRef2.set({Total:{totalTrain:math},Timestamps:{outTrain:resultTime}},{merge:!0})})
captTrain=!1;saveTrain=!0}}
function captureTrain(){captTrain=!0;var date=new Date();var options={month:'short',day:'2-digit'};var options2={hour:'numeric',minute:'numeric',second:'numeric'};var resultDate=new Intl.DateTimeFormat('en-GB',options).format(date);var resultTime=new Intl.DateTimeFormat('en-GB',options2).format(date);changeState5();active2=!1;active3=!1;active4=!1;active6=!1;var user=firebase.auth().currentUser;var email=user.email;var DocRef2=db.collection(resultDate).doc(email);DocRef2.set({Timestamps:{inTrain:resultTime}},{merge:!0})
if(captAvai){var user=firebase.auth().currentUser;var email=user.email;var DocRef2=db.collection(resultDate).doc(email);DocRef2.get().then(function(doc){var inAvai=doc.data().Timestamps.inAvai;var a=inAvai.split(':');var b=resultTime.split(':');var minutes=(+a[0])*60+(+a[1])+(+a[2])/60;var minutes2=(+b[0])*60+(+b[1])+(+b[2])/60;var math=minutes2-minutes;DocRef2.set({Total:{Available:math},Timestamps:{outAvai:resultTime}},{merge:!0})})
captAvai=!1;saveAvai=!0}
if(captLunch){var user=firebase.auth().currentUser;var email=user.email;var DocRef2=db.collection(resultDate).doc(email);DocRef2.get().then(function(doc){var inLunch=doc.data().Timestamps.inLunch;var a=inLunch.split(':');var b=resultTime.split(':');var minutes=(+a[0])*60+(+a[1])+(+a[2])/60;var minutes2=(+b[0])*60+(+b[1])+(+b[2])/60;var math=minutes2-minutes;DocRef2.set({Total:{Lunch:math},Timestamps:{outLunch:resultTime}},{merge:!0})})
captLunch=!1;saveLunch=!0}
if(captProj){var user=firebase.auth().currentUser;var email=user.email;var DocRef2=db.collection(resultDate).doc(email);DocRef2.get().then(function(doc){var inProy=doc.data().Timestamps.inProy;var a=inProj.split(':');var b=resultTime.split(':');var minutes=(+a[0])*60+(+a[1])+(+a[2])/60;var minutes2=(+b[0])*60+(+b[1])+(+b[2])/60;var math=minutes2-minutes;DocRef2.set({Total:{Project:math},Timestamps:{outProj:resultTime}},{merge:!0})})
captProj=!1;saveProj=!0}
if(captBreak){var user=firebase.auth().currentUser;var email=user.email;var DocRef2=db.collection(resultDate).doc(email);DocRef2.get().then(function(doc){var inBreak=doc.data().Timestamps.inBreak;var a=inBreak.split(':');var b=resultTime.split(':');var minutes=(+a[0])*60+(+a[1])+(+a[2])/60;var minutes2=(+b[0])*60+(+b[1])+(+b[2])/60;var math=minutes2-minutes;DocRef2.set({Total:{Break:math},Timestamps:{outBreak:resultTime}},{merge:!0})})
captBreak=!1;saveBreak=!0}}
function captureProject(){captProj=!0;var date=new Date();var options={month:'short',day:'2-digit'};var options2={hour:'numeric',minute:'numeric',second:'numeric'};var resultDate=new Intl.DateTimeFormat('en-GB',options).format(date);var resultTime=new Intl.DateTimeFormat('en-GB',options2).format(date);changeState6();active2=!1;active3=!1;active4=!1;active5=!1;var user=firebase.auth().currentUser;var email=user.email;var DocRef2=db.collection(resultDate).doc(email);DocRef2.set({Timestamps:{inProj:resultTime}},{merge:!0})
if(captAvai){var user=firebase.auth().currentUser;var email=user.email;var DocRef2=db.collection(resultDate).doc(email);DocRef2.get().then(function(doc){var inAvai=doc.data().Timestamps.inAvai;var a=inAvai.split(':');var b=resultTime.split(':');var minutes=(+a[0])*60+(+a[1])+(+a[2])/60;var minutes2=(+b[0])*60+(+b[1])+(+b[2])/60;var math=minutes2-minutes;DocRef2.set({Total:{Available:math},Timestamps:{outAvai:resultTime}},{merge:!0})})
captAvai=!1;saveAvai=!0}
if(captLunch){var user=firebase.auth().currentUser;var email=user.email;var DocRef2=db.collection(resultDate).doc(email);DocRef2.get().then(function(doc){var inLunch=doc.data().Timestamps.inLunch;var a=inLunch.split(':');var b=resultTime.split(':');var minutes=(+a[0])*60+(+a[1])+(+a[2])/60;var minutes2=(+b[0])*60+(+b[1])+(+b[2])/60;var math=minutes2-minutes;DocRef2.set({Total:{Lunch:math},Timestamps:{outLunch:resultTime}},{merge:!0})})
captLunch=!1;saveLunch=!0}
if(captTrain){var user=firebase.auth().currentUser;var email=user.email;var DocRef2=db.collection(resultDate).doc(email);DocRef2.get().then(function(doc){var inTrain=doc.data().Timestamps.inTrain;var a=inTrain.split(':');var b=resultTime.split(':');var minutes=(+a[0])*60+(+a[1])+(+a[2])/60;var minutes2=(+b[0])*60+(+b[1])+(+b[2])/60;var math=minutes2-minutes;DocRef2.set({Total:{Train:math},Timestamps:{outIn:resultTime}},{merge:!0})})
captTrain=!1;saveTrain=!0}
if(captBreak){var user=firebase.auth().currentUser;var email=user.email;var DocRef2=db.collection(resultDate).doc(email);DocRef2.get().then(function(doc){var inBreak=doc.data().Timestamps.inBreak;var a=inBreak.split(':');var b=resultTime.split(':');var minutes=(+a[0])*60+(+a[1])+(+a[2])/60;var minutes2=(+b[0])*60+(+b[1])+(+b[2])/60;var math=minutes2-minutes;DocRef2.set({Total:{Break:math},Timestamps:{outBreak:resultTime}},{merge:!0})})
captBreak=!1;saveBreak=!0}}
function resetTest(){document.getElementById("my_timer2").innerHTML="00"+":"+"00"+":"+"00";document.getElementById("my_timer3").innerHTML="00"+":"+"00"+":"+"00";document.getElementById("my_timer4").innerHTML="00"+":"+"00"+":"+"00";document.getElementById("my_timer5").innerHTML="00"+":"+"00"+":"+"00";document.getElementById("my_timer6").innerHTML="00"+":"+"00"+":"+"00";active2=!1;active3=!1;active4=!1;active5=!1;active6=!1;console.log('Reset done')}